language: ruby
cache: bundler
rvm:
  - 2.2.3
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database contacts_directory_test;' -U postgres
  - bundle exec rake db:migrate --trace
script:
  - RAILS_ENV=test bundle exec rake test
services:
  - redis-server

