# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  database: contacts_directory
  pool: 5
  timeout: 5000
  host: localhost
  username: root
  password: ""

test:
  <<: *default
  adapter: mysql2
  database: contacts_directory_test
  pool: 5
  timeout: 5000
  host: localhost
  username: root
  password: ""

production:
  encoding: utf8
  pool: 15